inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'app/models/**.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'app/controllers/favorites**.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'
    - 'spec/support/select_date_helper.rb'
    - 'spec/factories/**.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'
